### ISSUE TITLE
actionscript only ?

### ISSUE THREAD

**Issue by mikakun** [monicanagent/cypherpoker#36]
Sorry I had no idea how to contact you.
I think this p2p poker is genius, i'm far less enthusiastic with the actionscript client & I'd like to see if you'd agree to develop (with me or by guiding me so I can work fast) an html5/js client for desktop browsers. maybe also unity later on.
let me know, i'm looking for a poker engine to launch a new room & this p2p architecture could fit so well with my concept (but not the actionscript in browser !).
thehairinthesoup@protonmail.com

**Comment by monicanagent** [comment]
Replied via email from contact@cypherpoker.org (and feel free to contact this email address in the future).
